version: "2.4"
name: bazel_remote
services:
  bazel-remote:
    container_name: bazel-remote-cache
    command:
      [
        "--max_size=50",
        "--experimental_remote_asset_api",
        "--host=127.0.0.1",
        "--profile_port=0",
        "--enable_endpoint_metrics",
      ]
    restart: always
    image: buchgr/bazel-remote-cache:latest
    user: $USER_ID:$GROUP_ID
    ports:
      - 8080:8080
      - 9092:9092
      - 6060:6060
    environment:
      BAZEL_REMOTE_GRPC_PORT: 9092
      BAZEL_REMOTE_ENABLE_ENDPOINT_METRICS: 1
    volumes:
      - $HOME/.cache/bazel/remote:/data:rw
